// Interface automatically generated by schemas-to-ts

export interface Todo {
  id: number;
  attributes: {
    createdAt: Date,
    updatedAt: Date,
    publishedAt?: Date,
    Title?: string,
    description?: string,
    isDone?: boolean,
  };
}
export interface Todo_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  description?: string;
  isDone?: boolean;
}

export interface Todo_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  description?: string;
  isDone?: boolean;
}

export interface Todo_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  description?: string;
  isDone?: boolean;
}
