// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Project } from '../../../project/content-types/project/project';
import { Project_Plain } from '../../../project/content-types/project/project';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ProjectItem {
  id: number;
  attributes: {
    createdAt: Date,
    updatedAt: Date,
    publishedAt?: Date,
    title: string,
    description?: string,
    image: { data: Media },
    project?: { data: Project },
  };
}
export interface ProjectItem_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  description?: string;
  image: Media;
  project?: Project_Plain;
}

export interface ProjectItem_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  description?: string;
  image: number;
  project?: number;
}

export interface ProjectItem_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  description?: string;
  image: AdminPanelRelationPropertyModification<Media>;
  project?: AdminPanelRelationPropertyModification<Project_Plain>;
}
