// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface About {
  id: number;
  attributes: {
    createdAt: Date,
    updatedAt: Date,
    publishedAt?: Date,
    title?: string,
    subTitle?: string,
    text?: any,
    image?: { data: Media },
  };
}
export interface About_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title?: string;
  subTitle?: string;
  text?: any;
  image?: Media;
}

export interface About_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title?: string;
  subTitle?: string;
  text?: any;
  image?: number;
}

export interface About_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title?: string;
  subTitle?: string;
  text?: any;
  image?: AdminPanelRelationPropertyModification<Media>;
}
