// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Project {
  id: number;
  attributes: {
    createdAt: Date,
    updatedAt: Date,
    publishedAt?: Date,
    title: string,
    description?: string,
    coverImage: { data: Media },
  };
}
export interface Project_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  description?: string;
  coverImage: Media;
}

export interface Project_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  description?: string;
  coverImage: number;
}

export interface Project_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  description?: string;
  coverImage: AdminPanelRelationPropertyModification<Media>;
}
